import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { SettingsService } from '../settings/settings.service';
import { AIProviderRegistry } from './ai-provider.registry';
import {
  ChatCompletionRequest,
  ChatCompletionResponse,
  AIProviderConfigMap,
} from './interfaces';

const DISCLAIMER =
  'This response is generated by an AI assistant and is not a substitute for professional veterinary advice. Please consult a licensed veterinarian for medical concerns.';

@Injectable()
export class AIService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly registry: AIProviderRegistry,
    private readonly settings: SettingsService,
  ) {}

  async generateCompletion(
    request: ChatCompletionRequest,
  ): Promise<ChatCompletionResponse> {
    const provider = this.registry.get(request.provider);
    if (!provider) {
      throw new BadRequestException(
        `Provider "${request.provider}" is not registered`,
      );
    }

    const configRecord = await this.prisma.aIProviderConfig.findFirst({
      where: { provider: request.provider, isActive: true },
    });

    let config: AIProviderConfigMap = {};
    if (configRecord?.configJson) {
      try {
        config = JSON.parse(configRecord.configJson) as AIProviderConfigMap;
      } catch {
        config = {};
      }
    }

    const apiKeySetting = await this.settings.getDecryptedValue(
      `ai.${request.provider}.apiKey`,
    );
    if (apiKeySetting && !(config as any).apiKey) {
      (config as any).apiKey = apiKeySetting;
    }

    const modelSetting = await this.settings.getDecryptedValue(
      `ai.${request.provider}.model`,
    );
    if (modelSetting && !(config as any).model) {
      (config as any).model = modelSetting;
    }

    if (!provider.validateConfig(config)) {
      throw new BadRequestException(
        `Provider "${request.provider}" is not properly configured`,
      );
    }

    let messages = request.messages;
    if (request.pageContext) {
      const pagePrompt = await this.settings.getDecryptedValue(
        `ai.prompt.${request.pageContext}`,
      );
      if (pagePrompt) {
        messages = [
          { role: 'system', content: pagePrompt },
          ...messages.filter((m) => m.role !== 'system'),
        ];
      }
    }

    let text = '';
    let usedProvider = request.provider;

    try {
      text = await provider.generateCompletion(messages, config);
    } catch (error) {
      const fallbackOrder = ['openai', 'anthropic'];
      const fallbackProviders = fallbackOrder.filter(
        (p) => p !== request.provider,
      );

      let fallbackSuccess = false;
      for (const fallbackId of fallbackProviders) {
        const fallbackProvider = this.registry.get(fallbackId);
        if (!fallbackProvider) continue;

        let fallbackConfig: AIProviderConfigMap = {};
        const fallbackRecord = await this.prisma.aIProviderConfig.findFirst({
          where: { provider: fallbackId, isActive: true },
        });
        if (fallbackRecord?.configJson) {
          try {
            fallbackConfig = JSON.parse(fallbackRecord.configJson);
          } catch {
            fallbackConfig = {};
          }
        }

        const fallbackApiKey = await this.settings.getDecryptedValue(
          `ai.${fallbackId}.apiKey`,
        );
        if (fallbackApiKey && !(fallbackConfig as any).apiKey) {
          (fallbackConfig as any).apiKey = fallbackApiKey;
        }
        const fallbackModel = await this.settings.getDecryptedValue(
          `ai.${fallbackId}.model`,
        );
        if (fallbackModel && !(fallbackConfig as any).model) {
          (fallbackConfig as any).model = fallbackModel;
        }

        if (!fallbackProvider.validateConfig(fallbackConfig)) continue;

        try {
          text = await fallbackProvider.generateCompletion(messages, fallbackConfig);
          usedProvider = fallbackId;
          fallbackSuccess = true;
          break;
        } catch {
          // noop: try next fallback
        }
      }

      if (!fallbackSuccess) {
        const testProvider = this.registry.get('test');
        if (testProvider && request.provider !== 'test') {
          text = await testProvider.generateCompletion(messages, {});
          usedProvider = 'test';
        } else {
          throw error;
        }
      }
    }

    return {
      text: `${DISCLAIMER}\n\n${text}`,
      disclaimer: true,
      provider: usedProvider,
    };
  }
}
