import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AIProviderRegistry } from './ai-provider.registry';
import {
  ChatCompletionRequest,
  ChatCompletionResponse,
  AIProviderConfigMap,
} from './interfaces';

const DISCLAIMER =
  'This response is generated by an AI assistant and is not a substitute for professional veterinary advice. Please consult a licensed veterinarian for medical concerns.';

@Injectable()
export class AIService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly registry: AIProviderRegistry,
  ) {}

  async generateCompletion(
    request: ChatCompletionRequest,
  ): Promise<ChatCompletionResponse> {
    const provider = this.registry.get(request.provider);
    if (!provider) {
      throw new BadRequestException(
        `Provider "${request.provider}" is not registered`,
      );
    }

    const configRecord = await this.prisma.aIProviderConfig.findFirst({
      where: { provider: request.provider, isActive: true },
    });

    let config: AIProviderConfigMap = {};
    if (configRecord?.configJson) {
      try {
        config = JSON.parse(configRecord.configJson) as AIProviderConfigMap;
      } catch {
        config = {};
      }
    }

    if (!provider.validateConfig(config)) {
      throw new BadRequestException(
        `Provider "${request.provider}" is not properly configured`,
      );
    }

    let text: string;
    try {
      text = await provider.generateCompletion(request.messages, config);
    } catch (error) {
      const testProvider = this.registry.get('test');
      if (testProvider && request.provider !== 'test') {
        text = await testProvider.generateCompletion(request.messages, {});
      } else {
        throw error;
      }
    }

    return {
      text: `${DISCLAIMER}\n\n${text}`,
      disclaimer: true,
      provider: request.provider,
    };
  }
}
