/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminVaccinationsIndexRouteImport } from './routes/_authenticated/admin/vaccinations/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminNoteTemplatesIndexRouteImport } from './routes/_authenticated/admin/note-templates/index'
import { Route as AuthenticatedAdminMedicationsIndexRouteImport } from './routes/_authenticated/admin/medications/index'
import { Route as AuthenticatedAdminLabPanelsIndexRouteImport } from './routes/_authenticated/admin/lab-panels/index'
import { Route as AuthenticatedAdminBillingInvoicesRouteImport } from './routes/_authenticated/admin/billing/invoices'
import { Route as AuthenticatedAdminBillingDashboardRouteImport } from './routes/_authenticated/admin/billing/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVaccinationsIndexRoute =
  AuthenticatedAdminVaccinationsIndexRouteImport.update({
    id: '/admin/vaccinations/',
    path: '/admin/vaccinations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNoteTemplatesIndexRoute =
  AuthenticatedAdminNoteTemplatesIndexRouteImport.update({
    id: '/admin/note-templates/',
    path: '/admin/note-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMedicationsIndexRoute =
  AuthenticatedAdminMedicationsIndexRouteImport.update({
    id: '/admin/medications/',
    path: '/admin/medications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLabPanelsIndexRoute =
  AuthenticatedAdminLabPanelsIndexRouteImport.update({
    id: '/admin/lab-panels/',
    path: '/admin/lab-panels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingInvoicesRoute =
  AuthenticatedAdminBillingInvoicesRouteImport.update({
    id: '/admin/billing/invoices',
    path: '/admin/billing/invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingDashboardRoute =
  AuthenticatedAdminBillingDashboardRouteImport.update({
    id: '/admin/billing/dashboard',
    path: '/admin/billing/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/billing/dashboard': typeof AuthenticatedAdminBillingDashboardRoute
  '/admin/billing/invoices': typeof AuthenticatedAdminBillingInvoicesRoute
  '/admin/lab-panels/': typeof AuthenticatedAdminLabPanelsIndexRoute
  '/admin/medications/': typeof AuthenticatedAdminMedicationsIndexRoute
  '/admin/note-templates/': typeof AuthenticatedAdminNoteTemplatesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/vaccinations/': typeof AuthenticatedAdminVaccinationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/billing/dashboard': typeof AuthenticatedAdminBillingDashboardRoute
  '/admin/billing/invoices': typeof AuthenticatedAdminBillingInvoicesRoute
  '/admin/lab-panels': typeof AuthenticatedAdminLabPanelsIndexRoute
  '/admin/medications': typeof AuthenticatedAdminMedicationsIndexRoute
  '/admin/note-templates': typeof AuthenticatedAdminNoteTemplatesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/vaccinations': typeof AuthenticatedAdminVaccinationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/billing/dashboard': typeof AuthenticatedAdminBillingDashboardRoute
  '/_authenticated/admin/billing/invoices': typeof AuthenticatedAdminBillingInvoicesRoute
  '/_authenticated/admin/lab-panels/': typeof AuthenticatedAdminLabPanelsIndexRoute
  '/_authenticated/admin/medications/': typeof AuthenticatedAdminMedicationsIndexRoute
  '/_authenticated/admin/note-templates/': typeof AuthenticatedAdminNoteTemplatesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/vaccinations/': typeof AuthenticatedAdminVaccinationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/admin/settings'
    | '/patients/$patientId'
    | '/admin/'
    | '/appointments/'
    | '/patients/'
    | '/users/'
    | '/admin/billing/dashboard'
    | '/admin/billing/invoices'
    | '/admin/lab-panels/'
    | '/admin/medications/'
    | '/admin/note-templates/'
    | '/admin/users/'
    | '/admin/vaccinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/admin/settings'
    | '/patients/$patientId'
    | '/admin'
    | '/appointments'
    | '/patients'
    | '/users'
    | '/admin/billing/dashboard'
    | '/admin/billing/invoices'
    | '/admin/lab-panels'
    | '/admin/medications'
    | '/admin/note-templates'
    | '/admin/users'
    | '/admin/vaccinations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/profile'
    | '/_authenticated/admin/settings'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/admin/'
    | '/_authenticated/appointments/'
    | '/_authenticated/patients/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/billing/dashboard'
    | '/_authenticated/admin/billing/invoices'
    | '/_authenticated/admin/lab-panels/'
    | '/_authenticated/admin/medications/'
    | '/_authenticated/admin/note-templates/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/vaccinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vaccinations/': {
      id: '/_authenticated/admin/vaccinations/'
      path: '/admin/vaccinations'
      fullPath: '/admin/vaccinations/'
      preLoaderRoute: typeof AuthenticatedAdminVaccinationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/note-templates/': {
      id: '/_authenticated/admin/note-templates/'
      path: '/admin/note-templates'
      fullPath: '/admin/note-templates/'
      preLoaderRoute: typeof AuthenticatedAdminNoteTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/medications/': {
      id: '/_authenticated/admin/medications/'
      path: '/admin/medications'
      fullPath: '/admin/medications/'
      preLoaderRoute: typeof AuthenticatedAdminMedicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/lab-panels/': {
      id: '/_authenticated/admin/lab-panels/'
      path: '/admin/lab-panels'
      fullPath: '/admin/lab-panels/'
      preLoaderRoute: typeof AuthenticatedAdminLabPanelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing/invoices': {
      id: '/_authenticated/admin/billing/invoices'
      path: '/admin/billing/invoices'
      fullPath: '/admin/billing/invoices'
      preLoaderRoute: typeof AuthenticatedAdminBillingInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing/dashboard': {
      id: '/_authenticated/admin/billing/dashboard'
      path: '/admin/billing/dashboard'
      fullPath: '/admin/billing/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminBillingDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAdminBillingDashboardRoute: typeof AuthenticatedAdminBillingDashboardRoute
  AuthenticatedAdminBillingInvoicesRoute: typeof AuthenticatedAdminBillingInvoicesRoute
  AuthenticatedAdminLabPanelsIndexRoute: typeof AuthenticatedAdminLabPanelsIndexRoute
  AuthenticatedAdminMedicationsIndexRoute: typeof AuthenticatedAdminMedicationsIndexRoute
  AuthenticatedAdminNoteTemplatesIndexRoute: typeof AuthenticatedAdminNoteTemplatesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminVaccinationsIndexRoute: typeof AuthenticatedAdminVaccinationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAdminBillingDashboardRoute:
    AuthenticatedAdminBillingDashboardRoute,
  AuthenticatedAdminBillingInvoicesRoute:
    AuthenticatedAdminBillingInvoicesRoute,
  AuthenticatedAdminLabPanelsIndexRoute: AuthenticatedAdminLabPanelsIndexRoute,
  AuthenticatedAdminMedicationsIndexRoute:
    AuthenticatedAdminMedicationsIndexRoute,
  AuthenticatedAdminNoteTemplatesIndexRoute:
    AuthenticatedAdminNoteTemplatesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedAdminVaccinationsIndexRoute:
    AuthenticatedAdminVaccinationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
