import { useState, useRef, useEffect } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { X, Sparkles, Send, Loader2, Copy, Check, AlertTriangle } from "lucide-react"
import { Button } from "../ui/button"
import { Separator } from "../ui/separator"
import { fetchWithAuth } from "../../lib/api"
import { toast } from "sonner"

interface ChatMessage {
  role: "user" | "assistant"
  content: string
}

export interface AIPanelProps {
  open: boolean
  onClose: () => void
  title: string
  systemPrompt: string
}

const DISCLAIMER_START = "This response is generated by an AI assistant"

function parseAIResponse(content: string): { body: string; disclaimer: string } {
  if (content.startsWith(DISCLAIMER_START)) {
    const nl2 = content.indexOf("\n\n")
    if (nl2 !== -1) {
      return { disclaimer: content.slice(0, nl2), body: content.slice(nl2 + 2) }
    }
  }
  return { body: content, disclaimer: "" }
}

function AIBubble({ content }: { content: string }) {
  const { body, disclaimer } = parseAIResponse(content)
  return (
    <div className="space-y-2">
      <div className="rounded-xl border bg-card px-4 py-3.5 text-sm text-foreground whitespace-pre-wrap leading-relaxed">
        {body}
      </div>
      {disclaimer && (
        <div className="flex items-start gap-1.5">
          <AlertTriangle className="h-3 w-3 shrink-0 mt-0.5 text-amber-500" />
          <p className="text-[10px] text-muted-foreground leading-snug">{disclaimer}</p>
        </div>
      )}
    </div>
  )
}

export function AIPanel({ open, onClose, title, systemPrompt }: AIPanelProps) {
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [input, setInput] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const sentInitial = useRef(false)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (open && systemPrompt && !sentInitial.current) {
      sentInitial.current = true
      sendMessage(systemPrompt, [])
    }
    if (!open) {
      sentInitial.current = false
      setMessages([])
      setError(null)
      setInput("")
    }
  }, [open]) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [messages, isLoading])

  async function sendMessage(content: string, prev: ChatMessage[]) {
    const next = [...prev, { role: "user" as const, content }]
    setMessages(next)
    setIsLoading(true)
    setError(null)
    try {
      const res = await fetchWithAuth("/v1/ai/chat", {
        method: "POST",
        body: JSON.stringify({ provider: "anthropic", messages: next }),
      }) as { text: string }
      setMessages([...next, { role: "assistant", content: res.text }])
    } catch (e) {
      setError(e instanceof Error ? e.message : "AI request failed")
    } finally {
      setIsLoading(false)
    }
  }

  function handleSend() {
    const trimmed = input.trim()
    if (!trimmed || isLoading) return
    setInput("")
    sendMessage(trimmed, messages)
  }

  function copyLast() {
    const last = [...messages].reverse().find((m) => m.role === "assistant")
    if (!last) return
    navigator.clipboard.writeText(last.content).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
      toast.success("Copied to clipboard")
    })
  }

  const hasResponse = messages.some((m) => m.role === "assistant")
  const followUps = messages.slice(2)

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ x: "100%" }}
          animate={{ x: 0 }}
          exit={{ x: "100%" }}
          transition={{ type: "spring", damping: 28, stiffness: 280 }}
          className="fixed right-0 top-0 z-[60] flex h-full w-full max-w-md flex-col bg-background shadow-2xl border-l"
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b px-5 py-4 shrink-0">
            <div className="flex items-center gap-2.5">
              <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10">
                <Sparkles className="h-3.5 w-3.5 text-primary" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">AI Assistant</p>
                <h3 className="text-sm font-medium leading-tight truncate max-w-[240px]">{title}</h3>
              </div>
            </div>
            <div className="flex items-center gap-1 shrink-0">
              {hasResponse && (
                <Button variant="ghost" size="icon" className="h-8 w-8" onClick={copyLast} title="Copy response">
                  {copied
                    ? <Check className="h-4 w-4 text-emerald-500" />
                    : <Copy className="h-4 w-4" />}
                </Button>
              )}
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={onClose}>
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
            {messages.length === 0 && !isLoading && !error && (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <Sparkles className="h-10 w-10 text-muted-foreground/20 mb-3" />
                <p className="text-sm text-muted-foreground">Preparing analysis…</p>
              </div>
            )}

            {/* Initial AI response (messages[1]) */}
            {messages[1] && <AIBubble content={messages[1].content} />}

            {/* Follow-up conversation */}
            {followUps.map((msg, i) => {
              if (msg.role === "user") {
                return (
                  <div key={i} className="flex justify-end">
                    <div className="rounded-xl bg-primary text-primary-foreground px-4 py-2.5 text-sm max-w-[85%]">
                      {msg.content}
                    </div>
                  </div>
                )
              }
              return <AIBubble key={i} content={msg.content} />
            })}

            {isLoading && (
              <div className="rounded-xl border bg-card px-4 py-3.5">
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  <span>Thinking…</span>
                </div>
              </div>
            )}

            {error && (
              <div className="rounded-xl border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
                {error}
              </div>
            )}

            <div ref={bottomRef} />
          </div>

          {/* Follow-up input — only shown once there's a response */}
          {hasResponse && (
            <>
              <Separator />
              <div className="px-5 py-4 shrink-0 space-y-2.5">
                <div className="flex items-center gap-2">
                  <input
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleSend()}
                    placeholder="Ask a follow-up question…"
                    disabled={isLoading}
                    className="flex-1 rounded-lg border bg-transparent px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring disabled:opacity-50"
                  />
                  <Button
                    size="icon"
                    className="h-9 w-9 shrink-0"
                    onClick={handleSend}
                    disabled={!input.trim() || isLoading}
                  >
                    <Send className="h-4 w-4" />
                  </Button>
                </div>
                <p className="text-[10px] text-muted-foreground">
                  AI responses may contain errors. Always verify clinical decisions with qualified staff.
                </p>
              </div>
            </>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  )
}
